  apiVersion: datasciencecluster.opendatahub.io/v1
  kind: DataScienceCluster
  metadata:
    name: odh-deployment
    namespace: odh
  spec:
    components:
      codeflare:
        managementState: Managed
      dashboard:
        managementState: Managed
      datasciencepipelines:
        managementState: Managed
      kserve:
        managementState: Managed
      modelmeshserving:
        managementState: Managed
      ray:
        managementState: Managed
      workbenches:
        managementState: Managed