# this also works (now)
# It required the service account for mcad to be granted additional accesss rights

apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  name: cjb-undercommited
spec:
  schedulingSpec:
    dispatchDuration:
      expected: 300
      limit: 600
  # selector:
  #   matchLabels:
  #     app: cjb-test-1?????
  resources:
    GenericItems:
    - replicas: 1
      custompodresources:
      - replicas: 7
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 200m
          memory: 2Gi
      generictemplate:
        apiVersion: kubeflow.org/v2beta1
        kind: MPIJob
        metadata:
          name: cjb-undercommited
          labels:
            app: cjb-undercommited
        spec:
          slotsPerWorker: 1 # mpi ranks per pod
          runPolicy:
            cleanPodPolicy: Running
            ttlSecondsAfterFinished: 60
          sshAuthMountPath: /home/mpiuser/.ssh
          mpiReplicaSpecs:
            Launcher:
              replicas: 1
              metadata:
                labels:
                  app: cjb-undercommited
              template:
                spec:
                  containers:
                  - image: mpioperator/mpi-pi:openmpi
                    name: mpi-launcher
                    securityContext:
                      runAsUser: 1000
                    command:
                    - mpirun
                    args:
                    - -n
                    - "6"
                    - /home/mpiuser/pi
                    resources:
                      limits:
                        cpu: 100m
                        memory: 1Gi
            Worker:
              replicas: 6 # number of pods
              template:
                metadata:
                  labels:
                    app: cjb-undercommited
                spec:
                  containers:
                  - image: mpioperator/mpi-pi:openmpi
                    name: mpi-worker
                    securityContext:
                      runAsUser: 1000
                    command:
                    - /usr/sbin/sshd
                    args:
                    - -De
                    - -f
                    - /home/mpiuser/.sshd_config
                    resources:
                      limits:
                        cpu: 100m
                        memory: 1Gi

# slots x Worker.replicas = ranks
