---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: nexodus-username
  namespace: nexodus
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: nexodus-creds-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.nexodussecret.key }}
