apiVersion: v1
kind: Service
metadata:
    name: nexodus-lb
    namespace: nexodus
spec:
    selector:
        app: nexodus-relay
    ports:
        - name: udp-port
            protocol: UDP
            port: 51820
            targetPort: 51820
    type: LoadBalancer
