apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: build-tool
  name: mcad-build
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to run a Maven build.
  workspaces:
    - description: The workspace consisting of mcad project
      name: source
  steps:
    - image: 'registry.access.redhat.com/ubi8/go-toolset:latest'
      args:
        - config
        - '--global'
        - '--add'
        - 'safe.directory'
        - '/workspace/source/multi-cluster-app-dispatcher'
      command:
        - git 
      name: gitsetup
      workingDir: $(workspaces.source.path)
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 4Gi
          cpu: '1'
    - image: 'registry.access.redhat.com/ubi8/go-toolset:latest'
      args:
        - '-alh'
      command:
        - ls
      name: ls
      workingDir: $(workspaces.source.path)
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 4Gi
          cpu: '1'
    - image: 'registry.access.redhat.com/ubi8/go-toolset:latest'
      args:
        - mcad-controller
      script: |
        #!/usr/bin/env sh
        git config --global --add safe.directory /workspace/source
        make mcad-controller
        
      name: mcad-controller
      workingDir: $(workspaces.source.path)
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 4Gi
          cpu: '1'
